title Aura-OS Installer (Linux Zen)
linux /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-zen
initrd /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-zen.img
options archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL% archisosearchurl=file:///run/archiso/bootmnt
